LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_CFLAGS += -DBOARD_BOOT_DEVICE=\"$(BOARD_BOOT_DEVICE)\"
ifneq ($(BOARD_BOOTIMAGE_PARTITION),)
    LOCAL_CFLAGS += -DBOARD_BOOTIMAGE_PARTITION=\"$(BOARD_BOOTIMAGE_PARTITION)\"
endif
ifneq ($(BOARD_RECOVERYIMAGE_PARTITION),)
    LOCAL_CFLAGS += -DBOARD_RECOVERYIMAGE_PARTITION=\"$(BOARD_RECOVERYIMAGE_PARTITION)\"
endif
LOCAL_SRC_FILES := bmlutils.c
LOCAL_MODULE := libbmlutils
LOCAL_MODULE_TAGS := eng

include $(BUILD_STATIC_LIBRARY)
